### ISSUE TITLE
Do you know of a way to add corners to the frosted glass element ? 

### ISSUE THREAD

**Issue by JordansplaceYT** [ozone10/Rainmeter-TranslucentRM#1]
![Frosted Example](https://user-images.githubusercontent.com/65009223/90350989-b784a200-e036-11ea-8402-cf6fcd4be185.png)

**Comment by ozone10** [comment]
Hi @JordansplaceYT,
TranslucentRM will apply frosted glass effect on all skin, even on transparent parts, because of this skins have to be simple rectangle, meaning no round corners, circle, triangle, ...
This is limitation using undocumented api, I cannot change this. 

In your example your skin has round corners, so frosted glass effect will be applied even in transparent part of corners.

Also for faster reply, next time you better to ask on https://forum.rainmeter.net/.
